### ISSUE TITLE
Empty explanation bug with ELK 0.5 in Protege.

### ISSUE THREAD

**Issue by matentzn** [liveontologies/elk-reasoner#53]
When using ELK 0.5 in Protege (awesome by the way! Thanks for that!), we frequently get no explanations for simple entailments. Here a small example ontology O:

```
Prefix: owl: <http://www.w3.org/2002/07/owl#>
Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix: xml: <http://www.w3.org/XML/1998/namespace>
Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>

Ontology: <http://www.test.org/elk>

ObjectProperty: <http://www.test.org/elk#partof>

Class: <http://www.test.org/elk#Nerve>

    SubClassOf: 
        <http://www.test.org/elk#partof> some <http://www.test.org/elk#PNS>
    
    
Class: <http://www.test.org/elk#PNS>

Class: <http://www.test.org/elk#Peripheral_Nerve>

    EquivalentTo: 
        <http://www.test.org/elk#Nerve>
         and (<http://www.test.org/elk#partof> some <http://www.test.org/elk#PNS>)
```

O entails that Peripheral_Nerve and Nerve are equivalent. ELK, in contrast to, say, HermiT, won't find an explanation for that entailment; However, simply make Peripheral Nerve and Nerve disjoint (causing them to be unsatisfiable), and ELK find a suitable explanation. While this may not be a super urgent issue, it is quite an important one for us; If I can somehow help chasing this down (writing tests, or anything at all), I would be glad to.
